# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Photo.destroy_all
Comment.destroy_all
Tag.destroy_all

user1 = User.create(username: 'GuestAccount', password: 'password')
user2 = User.create(username: 'KatKnox', password: 'password')
user3 = User.create(username: 'SanFran4Life', password: 'password')
user4 = User.create(username: 'Bobby', password: 'password')
user5 = User.create(username: 'Lala', password: 'password')
user6 = User.create(username: 'FinalFantasy', password: 'password')
user7 = User.create(username: 'Squirtle', password: 'password')
user8 = User.create(username: 'Overclocked', password: 'password')
user9 = User.create(username: 'Kelly', password: 'password')
user10 = User.create(username: 'Animus', password: 'password')



photo1 = Photo.create(title: 'Sushi', description: 'Food in Japan', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203653/tokyo-2091357_1920_ebyuzu.jpg', user_id: user1.id)
photo2 = Photo.create(title: 'Sunny Day', description: 'Bikes are cool', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203654/summer-sport-bikes-bicycles_wkyz5g.jpg', user_id: user1.id)
photo3 = Photo.create(title: 'City Towers', description: 'Japan is fun', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203656/shinjuku-2190027_1920_g8lxh2.jpg', user_id: user1.id)
photo4 = Photo.create(title: 'Night Life', description: 'Japan at Night', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203652/shibuya-2223492_1920_za1dlr.jpg', user_id: user1.id)
photo5 = Photo.create(title: 'Foggy Bridge', description: 'San Francisco on a foggy day', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203652/san-francisco-2443452_1920_smwbte.jpg', user_id: user1.id)
photo6 = Photo.create(title: 'San Francisco Lights', description: 'View of TransAmerican', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203652/san-francisco-1633204_1920_wgpkro.jpg', user_id: user1.id)
photo7 = Photo.create(title: 'San Fran Night', description: 'Beautiful view of the city', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203652/san-francisco-1633203_1920_cdbnc2.jpg', user_id: user1.id)
photo8 = Photo.create(title: 'Lights Lights Lights', description: '', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203651/san-francisco-1633202_1920_o1wvty.jpg', user_id: user1.id)
photo9 = Photo.create(title: 'Eagle Eye', description: 'Bird watching', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203651/red-kite-bird-of-prey-milan-raptor-86462_ptciml.jpg', user_id: user1.id)
photo10 = Photo.create(title: 'Birds', description: 'Couple of colorful birds', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203652/rainbow-lorikeet-parrots-australia-rainbow-37833_kvzj69.jpg', user_id: user1.id)
photo11 = Photo.create(title: 'Camera Eye', description: 'Love picture taking', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203651/pexels-photo_sv37sh.jpg', user_id: user1.id)
photo12 = Photo.create(title: 'Eye in the Sky', description: 'Got a new toy', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203651/pexels-photo-518674_lwtdqy.jpg', user_id: user1.id)
photo13 = Photo.create(title: 'Lonely', description: 'Open road ahead', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203651/pexels-photo-512861_fiwdbn.jpg', user_id: user1.id)
photo14 = Photo.create(title: 'Bike Alone', description: 'Bikes on bikes', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203651/pexels-photo-504307_biw92r.jpg', user_id: user1.id)
photo15 = Photo.create(title: 'Beach Day', description: 'Sand in your toes', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203651/pexels-photo-500044_hgxelk.jpg', user_id: user1.id)
photo16 = Photo.create(title: 'Public Day', description: 'Bike on street', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203650/pexels-photo-494951_wqtmhy.jpg', user_id: user1.id)
photo17 = Photo.create(title: 'Paradise', description: 'Was a hot day', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203650/pexels-photo-490951_d3pt0s.jpg', user_id: user1.id)
photo18 = Photo.create(title: 'Vintage Setup', description: 'Stay at home day', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203650/pexels-photo-487426_a3jdh8.jpg', user_id: user1.id)
photo19 = Photo.create(title: 'Rock Tower', description: 'Balance is key', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203650/pexels-photo-484701_h7sc0o.jpg', user_id: user1.id)
photo20 = Photo.create(title: 'Bike Love', description: 'My baby', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203650/pexels-photo-478442_ejjzhf.jpg', user_id: user1.id)
photo21 = Photo.create(title: 'Home Day', description: 'My view from home', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203650/pexels-photo-436784_fpzziv.jpg', user_id: user1.id)
photo22 = Photo.create(title: 'Fantasy', description: 'Space journey', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203650/pexels-photo-414826_z6rjvc.jpg', user_id: user1.id)
photo23 = Photo.create(title: 'Tech Life', description: 'Cant live without em', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203649/pexels-photo-286565_rzvupb.jpg', user_id: user1.id)
photo24 = Photo.create(title: 'Note Taking', description: 'Need these for everyday operation', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203649/pexels-photo-265610_ei94kc.jpg', user_id: user1.id)
photo25 = Photo.create(title: 'Workload', description: 'Getting buried in studies', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501203648/pexels-photo-261909_gwark9.jpg', user_id: user1.id)
photo26 = Photo.create(title: 'Serenity', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo27 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo28 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo29 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo30 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo31 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo32 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo33 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo34 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo35 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo36 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo37 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo38 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo39 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo40 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo41 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo42 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo43 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo44 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo45 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo46 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo47 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo48 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo49 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
photo50 = Photo.create(title: 'Lens', description: 'Focus', image_url: 'http://res.cloudinary.com/iso100app/image/upload/v1501110884/background_il73yx.jpg', user_id: user1.id)
